/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ZBAR.h
 #	source generated by 4D Plugin Wizard
 #	Project : ZBAR
 #	author : miyako
 #	2020/06/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_ZBAR_H
#define PLUGIN_ZBAR_H

#include "4DPluginAPI.h"

#include "4DPlugin-JSON.h"

#include "zbar.h"

#if VERSIONWIN
#ifndef max
#define max(a,b) (((a) > (b)) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) (((a) < (b)) ? (a) : (b))
#endif
#include <gdiplus.h>
#else
#import <CoreGraphics/CoreGraphics.h>
#endif

#pragma mark -

void ZBAR(PA_PluginParameters params);

#endif /* PLUGIN_ZBAR_H */
