/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : ZBAR
 #	author : miyako
 #	2016/04/21
 #
 # --------------------------------------------------------------------------------*/



// --- ZBAR
void ZBAR(sLONG_PTR *pResult, PackagePtr pParams);

#include "zbar.h"

#if VERSIONWIN
#include <gdiplus.h>
#endif